// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxIS_XJqpbl-IwKR0I7gqNlJZvGouWWs',
    appId: '1:395193582854:web:16a872c4c92b77d3a54a87',
    messagingSenderId: '395193582854',
    projectId: 'project-cuoi-ky-595c4',
    authDomain: 'project-cuoi-ky-595c4.firebaseapp.com',
    storageBucket: 'project-cuoi-ky-595c4.firebasestorage.app',
    measurementId: 'G-M2XDR3M0CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSzekLKopYLaWKOjITYsjAfKgMKtiOBOs',
    appId: '1:395193582854:android:7e9575324301f94aa54a87',
    messagingSenderId: '395193582854',
    projectId: 'project-cuoi-ky-595c4',
    storageBucket: 'project-cuoi-ky-595c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ72_1uX2xG7iEXBFFDK741f7VLDEpu3E',
    appId: '1:395193582854:ios:d26f20806b8d6feca54a87',
    messagingSenderId: '395193582854',
    projectId: 'project-cuoi-ky-595c4',
    storageBucket: 'project-cuoi-ky-595c4.firebasestorage.app',
    iosBundleId: 'com.example.projectCuoiKy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ72_1uX2xG7iEXBFFDK741f7VLDEpu3E',
    appId: '1:395193582854:ios:d26f20806b8d6feca54a87',
    messagingSenderId: '395193582854',
    projectId: 'project-cuoi-ky-595c4',
    storageBucket: 'project-cuoi-ky-595c4.firebasestorage.app',
    iosBundleId: 'com.example.projectCuoiKy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGxIS_XJqpbl-IwKR0I7gqNlJZvGouWWs',
    appId: '1:395193582854:web:d8f97d39b2088b3ba54a87',
    messagingSenderId: '395193582854',
    projectId: 'project-cuoi-ky-595c4',
    authDomain: 'project-cuoi-ky-595c4.firebaseapp.com',
    storageBucket: 'project-cuoi-ky-595c4.firebasestorage.app',
    measurementId: 'G-KBVPKBBZT2',
  );
}
